apiVersion: v1
kind: Service
metadata:
  name: sungji-backend
  namespace: sungji-phone
  labels:
    app: sungji-phone
    component: backend
spec:
  type: ClusterIP
  selector:
    app: sungji-phone
    component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
