apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: sungji-phone
  labels:
    app: sungji-phone
    component: grafana
spec:
  type: ClusterIP
  selector:
    app: sungji-phone
    component: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
