apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: sungji-phone
  labels:
    app: sungji-phone
    component: prometheus
spec:
  type: ClusterIP
  selector:
    app: sungji-phone
    component: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
